/**
 * Remedy Report Database Operations
 *
 * IMPORTANT: This module is server-only and cannot be imported in client components.
 */

import "server-only";
import { prisma } from "./client";

/**
 * Create a new report (initially in "generating" status)
 */
export async function createReport(
  userId: string,
  data: {
    title: string;
    queryType: string;
    queryInput: string;
  },
) {
  return prisma.remedyReport.create({
    data: {
      userId,
      title: data.title,
      queryType: data.queryType,
      queryInput: data.queryInput,
      content: {},
      status: "generating",
    },
  });
}

/**
 * Update report with generated content
 */
export async function updateReportContent(
  id: string,
  content: object,
  status: "complete" | "failed",
) {
  return prisma.remedyReport.update({
    where: { id },
    data: { content, status },
  });
}

/**
 * Get a single report by ID
 */
export async function getReportById(id: string) {
  return prisma.remedyReport.findUnique({ where: { id } });
}

/**
 * Get reports for a user (paginated)
 */
export async function getUserReports(userId: string, page = 1, pageSize = 10) {
  const [reports, total] = await Promise.all([
    prisma.remedyReport.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      skip: (page - 1) * pageSize,
      take: pageSize,
    }),
    prisma.remedyReport.count({ where: { userId } }),
  ]);

  return { reports, total, page, pageSize };
}

/**
 * Delete a report
 */
export async function deleteReport(id: string) {
  return prisma.remedyReport.delete({ where: { id } });
}

/**
 * Count reports generated by a user in the current month
 */
export async function countMonthlyReports(userId: string): Promise<number> {
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

  return prisma.remedyReport.count({
    where: {
      userId,
      createdAt: { gte: startOfMonth },
      status: { not: "failed" },
    },
  });
}
