import type { Metadata } from "next";
import { headers } from "next/headers";
import { Fraunces, IBM_Plex_Mono, Manrope } from "next/font/google";
import { Providers } from "@/components/providers";
import { PWARegister } from "@/components/PWARegister";
import { Analytics } from "@/components/analytics";
import { Header } from "@/components/ui/header";
import { Separator } from "@/components/ui/separator";
import {
  generateOrganizationSchema,
  generateWebSiteSchema,
} from "@/lib/structured-data";
import { getBaseUrl } from "@/lib/url";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["400", "500"],
  display: "swap",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Remedi - Natural Alternatives to Pharmaceuticals",
    template: "%s | Remedi",
  },
  description:
    "Discover evidence-based natural remedies and alternatives to pharmaceutical drugs and supplements. Find safe, effective herbal and nutritional options backed by scientific research.",
  keywords: [
    "natural remedies",
    "herbal medicine",
    "pharmaceutical alternatives",
    "natural supplements",
    "holistic health",
    "alternative medicine",
    "herbal supplements",
    "natural health",
    "wellness",
    "nutrition",
  ],
  authors: [{ name: "Remedi Team" }],
  creator: "Remedi",
  publisher: "Remedi",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(getBaseUrl()),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "/",
    siteName: "Remedi",
    title: "Remedi - Natural Alternatives to Pharmaceuticals",
    description:
      "Discover evidence-based natural remedies and alternatives to pharmaceutical drugs and supplements.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Remedi - Natural Alternatives to Pharmaceuticals",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Remedi - Natural Alternatives to Pharmaceuticals",
    description:
      "Discover evidence-based natural remedies and alternatives to pharmaceutical drugs and supplements.",
    images: ["/og-image.png"],
    creator: "@remedi",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {},
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Remedi",
  },
  applicationName: "Remedi",
  icons: {
    icon: [
      { url: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/icons/icon-152x152.png", sizes: "152x152", type: "image/png" },
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the per-request nonce generated by middleware (proxy.ts) and forwarded
  // via x-nonce. Passed to script components so they satisfy the nonce-based CSP.
  const nonce = (await headers()).get("x-nonce") ?? "";

  const organizationSchema = generateOrganizationSchema();
  const webSiteSchema = generateWebSiteSchema();

  // Structured data is generated server-side from trusted internal functions,
  // not from user input, so it is safe to serialize here.
  const orgSchemaJson = JSON.stringify(organizationSchema);
  const webSchemaJson = JSON.stringify(webSiteSchema);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${manrope.variable} ${ibmPlexMono.variable} ${fraunces.variable}`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: orgSchemaJson }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: webSchemaJson }}
        />
      </head>
      <body className="font-sans antialiased min-h-screen bg-background text-foreground">
        <a href="#main-content" className="skip-to-main">
          Skip to main content
        </a>
        <Providers>
          <Header />
          <div id="main-content">{children}</div>
          <Footer />
          <PWARegister />
        </Providers>
        <Analytics
          plausibleDomain={process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
          googleAnalyticsId={process.env.NEXT_PUBLIC_GA_ID}
          nonce={nonce}
        />
      </body>
    </html>
  );
}

function Footer() {
  return (
    <footer className="border-t border-primary/10 bg-card/60 backdrop-blur-sm">
      <div className="mx-auto max-w-7xl px-4 py-8 md:px-8">
        <Separator className="mb-6" />
        <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
          <p className="text-sm text-muted-foreground">
            Remedi. For informational purposes only.
          </p>
          <nav className="flex gap-4">
            <a
              href="/faq"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              FAQ
            </a>
            <a
              href="/about"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              About
            </a>
          </nav>
        </div>
      </div>
    </footer>
  );
}
