// Traditional Chinese Medicine (TCM) Herbs
export const tcmRemedies = [
  {
    name: 'Astragalus (Huang Qi)',
    description: 'A foundational TCM herb used to strengthen the body\'s protective energy (Wei Qi) and support immune function.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Astragalus membranaceus root', 'Polysaccharides', 'Saponins', 'Flavonoids']),
    benefits: JSON.stringify(['Immune system support', 'Energy enhancement', 'Cardiovascular health', 'Anti-aging properties', 'Respiratory health']),
    usage: 'Take as directed on product label, typically 500-2000mg daily of standardized extract.',
    dosage: '500-2000mg standardized extract daily, or 3-6g dried root in decoction',
    precautions: 'May interact with immunosuppressant medications. Avoid during acute infections with fever.',
    scientificInfo: 'Research shows astragalus polysaccharides enhance immune cell activity and have adaptogenic properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2014', 'Phytomedicine 2016', 'Chinese Medicine 2018']),
    relatedRemedies: JSON.stringify(['Reishi Mushroom', 'Eleuthero', 'Codonopsis']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Codonopsis (Dang Shen)',
    description: 'A gentle Qi tonic herb used as a milder alternative to ginseng for building energy and supporting digestion.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Codonopsis pilosula root', 'Polysaccharides', 'Saponins', 'Alkaloids']),
    benefits: JSON.stringify(['Energy support', 'Digestive health', 'Immune function', 'Blood sugar regulation', 'Appetite improvement']),
    usage: 'Take 3-9g dried root in decoction or 500-1500mg extract daily.',
    dosage: '3-9g dried root or 500-1500mg extract daily',
    precautions: 'Generally well-tolerated. May enhance effects of blood sugar medications.',
    scientificInfo: 'Studies show codonopsis enhances digestive function and has immunomodulating properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2015', 'Chinese Journal of Integrative Medicine 2017']),
    relatedRemedies: JSON.stringify(['Astragalus', 'Ginseng', 'White Atractylodes']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'White Atractylodes (Bai Zhu)',
    description: 'A TCM herb that tonifies Spleen Qi and dries dampness, supporting digestive function and energy.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Atractylodes macrocephala rhizome', 'Atractylone', 'Atractylenolide', 'Essential oils']),
    benefits: JSON.stringify(['Digestive support', 'Fluid balance', 'Energy enhancement', 'Appetite regulation', 'Immune modulation']),
    usage: 'Take 6-12g in decoction or as directed in formula.',
    dosage: '6-12g dried rhizome in decoction',
    precautions: 'Use cautiously in conditions with Yin deficiency or heat signs.',
    scientificInfo: 'Research indicates atractylodes has gastroprotective and immunomodulating effects.',
    references: JSON.stringify(['Phytotherapy Research 2016', 'Journal of Ethnopharmacology 2018']),
    relatedRemedies: JSON.stringify(['Codonopsis', 'Poria', 'Licorice Root']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Poria (Fu Ling)',
    description: 'A medicinal fungus used to drain dampness, strengthen the spleen, and calm the mind.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Poria cocos sclerotium', 'Polysaccharides', 'Triterpenes', 'Pachymic acid']),
    benefits: JSON.stringify(['Fluid balance', 'Digestive health', 'Calming effects', 'Immune support', 'Sleep improvement']),
    usage: 'Take 9-15g in decoction or 500-1500mg extract daily.',
    dosage: '9-15g dried herb or 500-1500mg extract daily',
    precautions: 'May increase urination. Use cautiously with diuretic medications.',
    scientificInfo: 'Studies show poria polysaccharides have immunomodulating and diuretic properties.',
    references: JSON.stringify(['International Journal of Medicinal Mushrooms 2015', 'Journal of Ethnopharmacology 2017']),
    relatedRemedies: JSON.stringify(['White Atractylodes', 'Cinnamon', 'Licorice Root']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Rehmannia (Di Huang)',
    description: 'A blood and Yin tonic herb used to nourish the kidneys and support hormonal health.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Rehmannia glutinosa root', 'Catalpol', 'Iridoid glycosides', 'Polysaccharides']),
    benefits: JSON.stringify(['Kidney health', 'Blood nourishment', 'Hormonal balance', 'Anti-aging', 'Bone health']),
    usage: 'Take 9-30g prepared (Shu Di Huang) or 12-30g raw (Sheng Di) in decoction.',
    dosage: '9-30g in decoction depending on preparation',
    precautions: 'Raw form is cooling; prepared form is warming. May cause digestive upset in some people.',
    scientificInfo: 'Research shows rehmannia has nephroprotective and blood glucose-regulating effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Chinese Medicine 2019']),
    relatedRemedies: JSON.stringify(['Dioscorea', 'Cornus', 'Lycium']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Chinese Yam (Shan Yao)',
    description: 'A Qi and Yin tonic that supports digestive health, lung function, and kidney vitality.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Dioscorea opposita rhizome', 'Allantoin', 'Diosgenin', 'Mucilage', 'Starch']),
    benefits: JSON.stringify(['Digestive support', 'Lung health', 'Kidney tonification', 'Blood sugar balance', 'Fatigue relief']),
    usage: 'Take 15-30g in decoction or as food. Also available as powder or extract.',
    dosage: '15-30g dried herb or as food',
    precautions: 'Generally safe. May affect blood sugar levels.',
    scientificInfo: 'Studies show dioscorea has hypoglycemic and prebiotic effects.',
    references: JSON.stringify(['Journal of Food Science 2015', 'Carbohydrate Polymers 2018']),
    relatedRemedies: JSON.stringify(['Poria', 'Lotus Seed', 'Codonopsis']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Cornus Fruit (Shan Zhu Yu)',
    description: 'A sour herb that stabilizes the kidneys and liver, supporting essence and preventing leakage.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Cornus officinalis fruit', 'Loganin', 'Morroniside', 'Ursolic acid', 'Tannins']),
    benefits: JSON.stringify(['Kidney support', 'Liver health', 'Urinary control', 'Sweating regulation', 'Vision health']),
    usage: 'Take 6-12g in decoction or as part of traditional formulas.',
    dosage: '6-12g dried fruit in decoction',
    precautions: 'Avoid with difficult urination or excess dampness-heat conditions.',
    scientificInfo: 'Research indicates cornus has nephroprotective and hepatoprotective properties.',
    references: JSON.stringify(['Phytomedicine 2017', 'Journal of Ethnopharmacology 2019']),
    relatedRemedies: JSON.stringify(['Rehmannia', 'Dioscorea', 'Lycium']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Peony Root (Bai Shao)',
    description: 'A blood-nourishing and liver-soothing herb used for pain relief and menstrual regulation.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Paeonia lactiflora root', 'Paeoniflorin', 'Paeonol', 'Benzoic acid', 'Tannins']),
    benefits: JSON.stringify(['Pain relief', 'Menstrual regulation', 'Muscle relaxation', 'Liver protection', 'Blood nourishment']),
    usage: 'Take 6-15g in decoction or as part of traditional formulas.',
    dosage: '6-15g dried root in decoction',
    precautions: 'Use cautiously during pregnancy. May interact with blood thinners.',
    scientificInfo: 'Paeoniflorin has demonstrated anti-inflammatory and analgesic effects in studies.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Angelica Sinensis', 'Ligusticum', 'Bupleurum']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Bupleurum (Chai Hu)',
    description: 'A liver-regulating herb that disperses stagnation and is used for stress, mood, and digestive issues.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Bupleurum chinense root', 'Saikosaponins', 'Essential oils', 'Polysaccharides']),
    benefits: JSON.stringify(['Stress relief', 'Liver regulation', 'Mood support', 'Fever reduction', 'Digestive comfort']),
    usage: 'Take 3-12g in decoction or as part of traditional formulas.',
    dosage: '3-12g dried root in decoction',
    precautions: 'High doses may cause nausea. Use cautiously with liver conditions.',
    scientificInfo: 'Saikosaponins have demonstrated hepatoprotective and anti-inflammatory properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2015', 'Phytomedicine 2017']),
    relatedRemedies: JSON.stringify(['White Peony', 'Scutellaria', 'Pinellia']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Scutellaria (Huang Qin)',
    description: 'A heat-clearing herb with broad antimicrobial and anti-inflammatory properties.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Scutellaria baicalensis root', 'Baicalin', 'Baicalein', 'Wogonin', 'Flavonoids']),
    benefits: JSON.stringify(['Inflammation reduction', 'Antimicrobial effects', 'Respiratory health', 'Digestive support', 'Anxiety relief']),
    usage: 'Take 3-12g in decoction or 250-500mg extract 2-3 times daily.',
    dosage: '3-12g dried root or 250-500mg extract 2-3x daily',
    precautions: 'May interact with medications metabolized by liver. Avoid during pregnancy.',
    scientificInfo: 'Baicalin and baicalein have shown potent anti-inflammatory and neuroprotective effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Frontiers in Pharmacology 2019']),
    relatedRemedies: JSON.stringify(['Coptis', 'Gardenia', 'Phellodendron']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Coptis (Huang Lian)',
    description: 'A potent heat-clearing and damp-draining herb with strong antimicrobial properties.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Coptis chinensis rhizome', 'Berberine', 'Coptisine', 'Palmatine', 'Alkaloids']),
    benefits: JSON.stringify(['Antimicrobial action', 'Blood sugar support', 'Digestive health', 'Heart health', 'Inflammation reduction']),
    usage: 'Take 1.5-9g in decoction or berberine supplements as directed.',
    dosage: '1.5-9g dried rhizome or berberine 500-1500mg daily',
    precautions: 'Very bitter and cold. May interact with many medications. Avoid during pregnancy.',
    scientificInfo: 'Berberine has extensive research supporting metabolic and antimicrobial benefits.',
    references: JSON.stringify(['Metabolism 2017', 'Journal of Ethnopharmacology 2019', 'Frontiers in Pharmacology 2020']),
    relatedRemedies: JSON.stringify(['Scutellaria', 'Phellodendron', 'Goldenseal']),
    evidenceLevel: 'Strong'
  },
  {
    name: 'Phellodendron (Huang Bai)',
    description: 'A heat-clearing herb that drains damp-heat from the lower body, supporting urinary and reproductive health.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Phellodendron amurense bark', 'Berberine', 'Phellodendrine', 'Obaculactone']),
    benefits: JSON.stringify(['Urinary tract health', 'Joint support', 'Antimicrobial effects', 'Inflammation reduction', 'Skin health']),
    usage: 'Take 3-12g in decoction or as part of traditional formulas.',
    dosage: '3-12g dried bark in decoction',
    precautions: 'Very cold in nature. Avoid with cold conditions or weak digestion.',
    scientificInfo: 'Contains berberine with documented antimicrobial and anti-inflammatory effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Coptis', 'Anemarrhena', 'Rehmannia']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Anemarrhena (Zhi Mu)',
    description: 'A Yin-nourishing herb that clears heat and moistens dryness, often paired with Phellodendron.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Anemarrhena asphodeloides rhizome', 'Timosaponins', 'Mangiferin', 'Sarsasapogenin']),
    benefits: JSON.stringify(['Fever reduction', 'Yin nourishment', 'Thirst relief', 'Blood sugar support', 'Respiratory health']),
    usage: 'Take 6-12g in decoction or as part of traditional formulas.',
    dosage: '6-12g dried rhizome in decoction',
    precautions: 'Cold in nature. Avoid with diarrhea or weak digestion.',
    scientificInfo: 'Timosaponins have shown neuroprotective and anti-diabetic properties in research.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytomedicine 2019']),
    relatedRemedies: JSON.stringify(['Phellodendron', 'Rehmannia', 'Ophiopogon']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Ophiopogon (Mai Men Dong)',
    description: 'A Yin-nourishing herb that moistens the lungs and heart, supporting respiratory and cardiovascular health.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Ophiopogon japonicus tuber', 'Ophiopogonins', 'Polysaccharides', 'Homoisoflavonoids']),
    benefits: JSON.stringify(['Lung moisture', 'Heart nourishment', 'Thirst relief', 'Constipation relief', 'Skin hydration']),
    usage: 'Take 6-15g in decoction or as part of traditional formulas.',
    dosage: '6-15g dried tuber in decoction',
    precautions: 'May cause loose stools in some individuals. Avoid with phlegm-damp conditions.',
    scientificInfo: 'Research shows ophiopogon polysaccharides have cardioprotective and immunomodulating effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Carbohydrate Polymers 2018']),
    relatedRemedies: JSON.stringify(['Adenophora', 'Lily Bulb', 'Asparagus Root']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Salvia Root (Dan Shen)',
    description: 'A blood-moving herb with strong cardiovascular benefits, used for heart health and circulation.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Salvia miltiorrhiza root', 'Tanshinones', 'Salvianolic acids', 'Diterpenoids']),
    benefits: JSON.stringify(['Heart health', 'Blood circulation', 'Pain relief', 'Antioxidant protection', 'Liver health']),
    usage: 'Take 9-15g in decoction or standardized extract as directed.',
    dosage: '9-15g dried root or standardized extract',
    precautions: 'May interact with blood thinners and cardiovascular medications. Avoid during pregnancy.',
    scientificInfo: 'Tanshinones and salvianolic acids have demonstrated cardioprotective effects in clinical studies.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2018', 'Frontiers in Pharmacology 2019', 'Circulation Research 2020']),
    relatedRemedies: JSON.stringify(['Safflower', 'Peach Kernel', 'Red Peony']),
    evidenceLevel: 'Strong'
  },
  {
    name: 'Safflower (Hong Hua)',
    description: 'A blood-invigorating herb used to promote circulation and relieve pain from blood stasis.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Carthamus tinctorius flower', 'Carthamin', 'Safflower yellow', 'Flavonoids']),
    benefits: JSON.stringify(['Blood circulation', 'Pain relief', 'Menstrual regulation', 'Bruise healing', 'Cardiovascular support']),
    usage: 'Take 3-9g in decoction. Lower doses move blood; higher doses can break blood stasis.',
    dosage: '3-9g dried flowers in decoction',
    precautions: 'Avoid during pregnancy. Use cautiously with blood thinners.',
    scientificInfo: 'Research shows safflower has antiplatelet and circulation-enhancing effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytomedicine 2019']),
    relatedRemedies: JSON.stringify(['Dan Shen', 'Peach Kernel', 'Angelica']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Cinnamon Bark (Rou Gui)',
    description: 'A warming herb that tonifies kidney Yang, warms the body, and promotes circulation.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Cinnamomum cassia bark', 'Cinnamaldehyde', 'Cinnamic acid', 'Eugenol', 'Coumarin']),
    benefits: JSON.stringify(['Warming circulation', 'Kidney Yang support', 'Pain relief', 'Blood sugar regulation', 'Digestive aid']),
    usage: 'Take 1-4.5g in decoction (added at end of cooking) or as powder/capsule.',
    dosage: '1-4.5g dried bark or 500-2000mg powder',
    precautions: 'Very warming. Avoid with Yin deficiency, heat conditions, or pregnancy. High coumarin content.',
    scientificInfo: 'Cinnamaldehyde has demonstrated blood sugar-regulating and antimicrobial effects.',
    references: JSON.stringify(['Diabetes Care 2003', 'Journal of Ethnopharmacology 2017']),
    relatedRemedies: JSON.stringify(['Aconite', 'Dried Ginger', 'Eucommia']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Eucommia Bark (Du Zhong)',
    description: 'A kidney and liver tonic that strengthens bones and tendons, used for back pain and pregnancy support.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Eucommia ulmoides bark', 'Aucubin', 'Geniposidic acid', 'Chlorogenic acid', 'Lignans']),
    benefits: JSON.stringify(['Bone health', 'Tendon strength', 'Back pain relief', 'Blood pressure support', 'Pregnancy support']),
    usage: 'Take 9-15g in decoction or as extract.',
    dosage: '9-15g dried bark or 500-1000mg extract',
    precautions: 'Generally safe. May lower blood pressure.',
    scientificInfo: 'Studies show eucommia has hypotensive and bone-strengthening properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Loranthus', 'Dipsacus', 'Drynaria']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Loranthus (Sang Ji Sheng)',
    description: 'A herb that tonifies liver and kidney, strengthens bones, and benefits pregnancy.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Taxillus chinensis stems', 'Flavonoids', 'Quercetin', 'Avicularin']),
    benefits: JSON.stringify(['Bone and tendon health', 'Joint support', 'Pregnancy support', 'Blood pressure regulation', 'Pain relief']),
    usage: 'Take 9-15g in decoction.',
    dosage: '9-15g dried herb in decoction',
    precautions: 'Generally safe when used appropriately.',
    scientificInfo: 'Contains flavonoids with antioxidant and anti-inflammatory properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2015', 'Chinese Medicine 2017']),
    relatedRemedies: JSON.stringify(['Eucommia', 'Dipsacus', 'Cuscuta']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Cuscuta Seed (Tu Si Zi)',
    description: 'A kidney and liver tonic that supports reproductive health and vision.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Cuscuta chinensis seed', 'Flavonoids', 'Quercetin', 'Kaempferol', 'Polysaccharides']),
    benefits: JSON.stringify(['Reproductive health', 'Vision support', 'Kidney tonification', 'Urinary control', 'Anti-aging']),
    usage: 'Take 9-15g in decoction or as part of traditional formulas.',
    dosage: '9-15g dried seed in decoction',
    precautions: 'Avoid with constipation from Yin deficiency or kidney fire.',
    scientificInfo: 'Research shows cuscuta has hepatoprotective and immunomodulating effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Lycium', 'Ligustrum', 'Eclipta']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Ligustrum (Nu Zhen Zi)',
    description: 'A Yin-nourishing herb that supports liver and kidney, benefits vision, and promotes hair health.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Ligustrum lucidum fruit', 'Oleanolic acid', 'Ursolic acid', 'Salidroside', 'Tyrosol']),
    benefits: JSON.stringify(['Vision health', 'Hair health', 'Liver protection', 'Kidney nourishment', 'Immune support']),
    usage: 'Take 9-15g in decoction or as extract.',
    dosage: '9-15g dried fruit or standardized extract',
    precautions: 'Cold in nature. Avoid with diarrhea from Spleen deficiency.',
    scientificInfo: 'Contains compounds with hepatoprotective and immunomodulating effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytotherapy Research 2019']),
    relatedRemedies: JSON.stringify(['Eclipta', 'Lycium', 'Mulberry']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Eclipta (Mo Han Lian)',
    description: 'A cooling herb that nourishes liver and kidney Yin, supports hair health, and stops bleeding.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Eclipta prostrata herb', 'Wedelolactone', 'Ecliptasaponins', 'Coumestans']),
    benefits: JSON.stringify(['Hair health', 'Liver protection', 'Bleeding control', 'Vision support', 'Anti-aging']),
    usage: 'Take 9-15g in decoction or as extract.',
    dosage: '9-15g dried herb or standardized extract',
    precautions: 'Cold in nature. Use cautiously with cold conditions or weak digestion.',
    scientificInfo: 'Wedelolactone has shown hepatoprotective and anti-inflammatory effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Ligustrum', 'He Shou Wu', 'Mulberry']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Lycium Fruit (Gou Qi Zi)',
    description: 'A nourishing berry that benefits liver and kidney, supports vision, and promotes longevity.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Lycium barbarum fruit', 'Zeaxanthin', 'Beta-carotene', 'Polysaccharides', 'Betaine']),
    benefits: JSON.stringify(['Vision health', 'Liver support', 'Kidney nourishment', 'Immune function', 'Anti-aging']),
    usage: 'Take 6-18g dried berries daily or as tea/food.',
    dosage: '6-18g dried berries or 500-3000mg extract',
    precautions: 'May interact with blood thinners. Avoid excessive amounts with diarrhea.',
    scientificInfo: 'Rich in zeaxanthin and polysaccharides with demonstrated eye health and immune benefits.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Food Chemistry 2019', 'Nutrients 2020']),
    relatedRemedies: JSON.stringify(['Chrysanthemum', 'Mulberry', 'Ligustrum']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Chrysanthemum (Ju Hua)',
    description: 'A cooling flower that clears liver heat, benefits the eyes, and calms headaches.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Chrysanthemum morifolium flower', 'Flavonoids', 'Apigenin', 'Luteolin', 'Essential oils']),
    benefits: JSON.stringify(['Eye health', 'Headache relief', 'Liver cooling', 'Blood pressure support', 'Detoxification']),
    usage: 'Brew 3-9g as tea or take in decoction.',
    dosage: '3-9g dried flowers as tea or decoction',
    precautions: 'Cool in nature. Avoid with cold conditions or diarrhea.',
    scientificInfo: 'Flavonoids provide antioxidant and anti-inflammatory benefits.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Food and Chemical Toxicology 2018']),
    relatedRemedies: JSON.stringify(['Lycium', 'Mulberry Leaf', 'Cassia Seed']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Mulberry Leaf (Sang Ye)',
    description: 'A cooling herb that clears lung heat, benefits the eyes, and supports blood sugar regulation.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Morus alba leaf', 'DNJ (1-deoxynojirimycin)', 'Flavonoids', 'Chlorogenic acid']),
    benefits: JSON.stringify(['Blood sugar support', 'Eye health', 'Respiratory relief', 'Liver cooling', 'Antioxidant protection']),
    usage: 'Take 6-12g in decoction or as tea.',
    dosage: '6-12g dried leaf or as tea',
    precautions: 'May affect blood sugar. Use cautiously with diabetes medications.',
    scientificInfo: 'DNJ has demonstrated alpha-glucosidase inhibiting effects for blood sugar control.',
    references: JSON.stringify(['Diabetes Research and Clinical Practice 2017', 'Journal of Ethnopharmacology 2019']),
    relatedRemedies: JSON.stringify(['Chrysanthemum', 'Cassia Seed', 'Apricot Seed']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Cassia Seed (Jue Ming Zi)',
    description: 'A liver-clearing herb that benefits the eyes, promotes bowel movements, and supports healthy blood pressure.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Cassia obtusifolia seed', 'Anthraquinones', 'Emodin', 'Chrysophanol', 'Aurantio-obtusin']),
    benefits: JSON.stringify(['Eye health', 'Constipation relief', 'Blood pressure support', 'Liver clearing', 'Cholesterol management']),
    usage: 'Take 9-15g in decoction or brew as tea.',
    dosage: '9-15g dried seeds or as tea',
    precautions: 'Laxative effect. Avoid with diarrhea or low blood pressure.',
    scientificInfo: 'Anthraquinones have laxative and lipid-lowering effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Chrysanthemum', 'Mulberry Leaf', 'Lycium']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Pinellia (Ban Xia)',
    description: 'A phlegm-resolving herb that dries dampness, stops vomiting, and dissipates nodules.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Pinellia ternata tuber', 'Ephedrine', 'Beta-sitosterol', 'Alkaloids', 'Starch']),
    benefits: JSON.stringify(['Phlegm reduction', 'Nausea relief', 'Nodule resolution', 'Digestive support', 'Respiratory clearing']),
    usage: 'Take 3-9g of processed (Zhi Ban Xia) in decoction. Raw form is toxic.',
    dosage: '3-9g processed tuber in decoction',
    precautions: 'Must use processed form only. Avoid during pregnancy. Raw form is toxic.',
    scientificInfo: 'Processing removes toxicity while preserving antiemetic properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2015', 'Chinese Medicine 2017']),
    relatedRemedies: JSON.stringify(['Chen Pi', 'Poria', 'Ginger']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tangerine Peel (Chen Pi)',
    description: 'An aromatic herb that regulates Qi, dries dampness, and transforms phlegm.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Citrus reticulata peel', 'Hesperidin', 'Limonene', 'Synephrine', 'Essential oils']),
    benefits: JSON.stringify(['Digestive comfort', 'Qi regulation', 'Phlegm reduction', 'Appetite improvement', 'Nausea relief']),
    usage: 'Take 3-9g in decoction or as part of formulas.',
    dosage: '3-9g dried peel in decoction',
    precautions: 'May cause dryness with excessive use. Use cautiously with Yin deficiency.',
    scientificInfo: 'Hesperidin has demonstrated anti-inflammatory and antioxidant effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytotherapy Research 2018']),
    relatedRemedies: JSON.stringify(['Pinellia', 'Poria', 'Licorice']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Fritillaria (Chuan Bei Mu)',
    description: 'A cooling herb that clears heat, transforms phlegm, and stops cough.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Fritillaria cirrhosa bulb', 'Peimine', 'Peiminine', 'Isoverticine', 'Alkaloids']),
    benefits: JSON.stringify(['Cough relief', 'Phlegm transformation', 'Lung moisture', 'Nodule resolution', 'Respiratory soothing']),
    usage: 'Take 3-9g in decoction or as powder.',
    dosage: '3-9g dried bulb or 1-3g powder',
    precautions: 'Cold in nature. Avoid with cold-type cough. Expensive herb.',
    scientificInfo: 'Alkaloids have demonstrated antitussive and expectorant effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytomedicine 2019']),
    relatedRemedies: JSON.stringify(['Apricot Seed', 'Mulberry Bark', 'Platycodon']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Platycodon (Jie Geng)',
    description: 'A lung-opening herb that transforms phlegm, promotes expectoration, and benefits the throat.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Platycodon grandiflorum root', 'Platycodins', 'Saponins', 'Inulin', 'Glucose']),
    benefits: JSON.stringify(['Phlegm expectoration', 'Throat health', 'Lung opening', 'Abscess drainage', 'Voice clarity']),
    usage: 'Take 3-9g in decoction.',
    dosage: '3-9g dried root in decoction',
    precautions: 'Dispersing nature. Avoid with coughing blood or Yin deficiency.',
    scientificInfo: 'Saponins have demonstrated expectorant and anti-inflammatory properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Licorice', 'Apricot Seed', 'Fritillaria']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Gardenia (Zhi Zi)',
    description: 'A bitter, cold herb that clears heat, drains fire, and cools blood, supporting liver and heart.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Gardenia jasminoides fruit', 'Geniposide', 'Crocin', 'Crocetin', 'Iridoids']),
    benefits: JSON.stringify(['Heat clearing', 'Blood cooling', 'Liver support', 'Anxiety relief', 'Inflammation reduction']),
    usage: 'Take 3-12g in decoction.',
    dosage: '3-12g dried fruit in decoction',
    precautions: 'Very cold. Avoid with loose stools from Spleen deficiency.',
    scientificInfo: 'Geniposide has shown neuroprotective and anti-inflammatory effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Frontiers in Pharmacology 2019']),
    relatedRemedies: JSON.stringify(['Scutellaria', 'Coptis', 'Phellodendron']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Moutan Bark (Mu Dan Pi)',
    description: 'A blood-cooling herb that clears deficiency heat, invigorates blood, and clears liver fire.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Paeonia suffruticosa bark', 'Paeonol', 'Paeonoside', 'Paeoniflorin', 'Essential oils']),
    benefits: JSON.stringify(['Blood cooling', 'Menstrual regulation', 'Bruise healing', 'Fever reduction', 'Inflammation relief']),
    usage: 'Take 6-12g in decoction.',
    dosage: '6-12g dried bark in decoction',
    precautions: 'Avoid during pregnancy and with heavy menstruation.',
    scientificInfo: 'Paeonol has demonstrated anti-inflammatory and antiplatelet effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Gardenia', 'Rehmannia', 'White Peony']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Alisma (Ze Xie)',
    description: 'A diuretic herb that drains dampness, promotes urination, and clears damp-heat.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Alisma orientale tuber', 'Alisol A', 'Alisol B', 'Triterpenes', 'Polysaccharides']),
    benefits: JSON.stringify(['Fluid drainage', 'Urination promotion', 'Blood lipid support', 'Dizziness relief', 'Edema reduction']),
    usage: 'Take 6-15g in decoction.',
    dosage: '6-15g dried tuber in decoction',
    precautions: 'Increases urination. Use cautiously with kidney deficiency or dehydration.',
    scientificInfo: 'Alisols have shown diuretic and lipid-lowering effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytomedicine 2019']),
    relatedRemedies: JSON.stringify(['Poria', 'Polyporus', 'Plantago Seed']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Plantago Seed (Che Qian Zi)',
    description: 'A cooling herb that promotes urination, clears heat, and benefits the eyes.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Plantago asiatica seed', 'Aucubin', 'Mucilage', 'Plantaginin', 'Fatty acids']),
    benefits: JSON.stringify(['Urination promotion', 'Eye health', 'Diarrhea relief', 'Heat clearing', 'Phlegm reduction']),
    usage: 'Take 9-15g in decoction (wrapped in cloth to prevent sticking).',
    dosage: '9-15g dried seed in decoction (wrapped)',
    precautions: 'May cause loose stools. Avoid with kidney Yang deficiency.',
    scientificInfo: 'Aucubin has demonstrated diuretic and anti-inflammatory properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytotherapy Research 2018']),
    relatedRemedies: JSON.stringify(['Alisma', 'Poria', 'Talc']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Magnolia Bark (Hou Po)',
    description: 'An aromatic herb that moves Qi, transforms dampness, and relieves fullness and distention.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Magnolia officinalis bark', 'Honokiol', 'Magnolol', 'Essential oils', 'Alkaloids']),
    benefits: JSON.stringify(['Digestive comfort', 'Qi movement', 'Anxiety relief', 'Respiratory support', 'Bloating reduction']),
    usage: 'Take 3-9g in decoction or honokiol/magnolol supplements as directed.',
    dosage: '3-9g dried bark or standardized extract',
    precautions: 'Drying in nature. Avoid during pregnancy.',
    scientificInfo: 'Honokiol and magnolol have demonstrated anxiolytic and anti-inflammatory effects.',
    references: JSON.stringify(['Neuropharmacology 2017', 'Journal of Ethnopharmacology 2019']),
    relatedRemedies: JSON.stringify(['Pinellia', 'Perilla', 'Ginger']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Hawthorn Berry (Shan Zha)',
    description: 'A digestive and cardiovascular herb that promotes food digestion and blood circulation.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Crataegus pinnatifida fruit', 'Vitexin', 'Quercetin', 'Oligomeric proanthocyanidins', 'Organic acids']),
    benefits: JSON.stringify(['Digestion of meat and fats', 'Heart health', 'Blood circulation', 'Cholesterol support', 'Blood pressure regulation']),
    usage: 'Take 9-15g in decoction or as tea/food.',
    dosage: '9-15g dried fruit or standardized extract',
    precautions: 'May interact with heart medications. Avoid with acid reflux.',
    scientificInfo: 'Flavonoids have demonstrated cardioprotective effects in clinical trials.',
    references: JSON.stringify(['Cochrane Database Systematic Reviews 2010', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Barley Sprout', 'Radish Seed', 'Chen Pi']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Polygonum (Ye Jiao Teng)',
    description: 'A calming herb that nourishes heart blood and relieves insomnia and dream-disturbed sleep.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Polygonum multiflorum stem', 'Stilbene glycosides', 'Flavonoids', 'Anthraquinones']),
    benefits: JSON.stringify(['Sleep improvement', 'Anxiety relief', 'Pain relief', 'Skin health', 'Blood nourishment']),
    usage: 'Take 9-15g in decoction, especially for sleep.',
    dosage: '9-15g dried stem in decoction',
    precautions: 'Different from He Shou Wu (root). Generally safe.',
    scientificInfo: 'Contains compounds with sedative and anxiolytic properties.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2015', 'Phytomedicine 2017']),
    relatedRemedies: JSON.stringify(['Sour Jujube Seed', 'Longan', 'Poria']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Sour Jujube Seed (Suan Zao Ren)',
    description: 'A premier calming herb that nourishes heart blood and liver Yin, promoting restful sleep.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Ziziphus jujuba var. spinosa seed', 'Jujubosides', 'Saponins', 'Flavonoids', 'Fatty acids']),
    benefits: JSON.stringify(['Sleep improvement', 'Anxiety relief', 'Heart nourishment', 'Sweating regulation', 'Liver Yin support']),
    usage: 'Take 9-18g in decoction or as extract. Raw for sleep; dry-fried for excessive sweating.',
    dosage: '9-18g dried seed or standardized extract',
    precautions: 'May cause drowsiness. Use cautiously with sedative medications.',
    scientificInfo: 'Jujubosides have demonstrated sedative and anxiolytic effects in research.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytomedicine 2019', 'Sleep Medicine Reviews 2020']),
    relatedRemedies: JSON.stringify(['Longan', 'Poria', 'Polygonum']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Longan Fruit (Long Yan Rou)',
    description: 'A sweet, warming fruit that nourishes heart blood and spleen Qi, calming the mind.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Dimocarpus longan aril', 'Polysaccharides', 'Flavonoids', 'Adenosine', 'Vitamins']),
    benefits: JSON.stringify(['Heart nourishment', 'Anxiety relief', 'Sleep improvement', 'Memory support', 'Blood building']),
    usage: 'Take 9-15g dried or fresh as food or in decoction.',
    dosage: '9-15g dried fruit or as food',
    precautions: 'Warming and sweet. Avoid with phlegm-heat or excess conditions.',
    scientificInfo: 'Contains compounds with antioxidant and neuroprotective properties.',
    references: JSON.stringify(['Food Chemistry 2016', 'Journal of Functional Foods 2018']),
    relatedRemedies: JSON.stringify(['Sour Jujube Seed', 'Ginseng', 'Astragalus']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Biota Seed (Bai Zi Ren)',
    description: 'A heart-nourishing herb that calms the spirit, moistens intestines, and benefits skin.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Platycladus orientalis seed', 'Fatty oils', 'Saponins', 'Flavonoids', 'Vitamin E']),
    benefits: JSON.stringify(['Heart nourishment', 'Anxiety relief', 'Sleep improvement', 'Constipation relief', 'Memory support']),
    usage: 'Take 9-18g in decoction or as part of formulas.',
    dosage: '9-18g dried seed in decoction',
    precautions: 'Oily and lubricating. Avoid with loose stools or diarrhea.',
    scientificInfo: 'Contains fatty acids and compounds that support cardiovascular health.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Sour Jujube Seed', 'Longan', 'Polygala']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Polygala (Yuan Zhi)',
    description: 'A calming herb that opens heart orifices, transforms phlegm, and enhances cognition.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Polygala tenuifolia root', 'Tenuigenin', 'Polygalasaponins', 'Xanthones', 'Oligosaccharides']),
    benefits: JSON.stringify(['Memory enhancement', 'Anxiety relief', 'Heart-kidney communication', 'Phlegm transformation', 'Focus improvement']),
    usage: 'Take 3-9g in decoction or as extract.',
    dosage: '3-9g dried root or standardized extract',
    precautions: 'May cause gastric irritation. Use processed form (Zhi Yuan Zhi) to reduce irritation.',
    scientificInfo: 'Tenuigenin and saponins have demonstrated neuroprotective and cognitive-enhancing effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Frontiers in Pharmacology 2019']),
    relatedRemedies: JSON.stringify(['Acorus', 'Poria', 'Sour Jujube Seed']),
    evidenceLevel: 'Moderate'
  },
  {
    name: 'Acorus (Shi Chang Pu)',
    description: 'An aromatic herb that opens orifices, transforms phlegm, and enhances mental clarity.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Acorus tatarinowii rhizome', 'Beta-asarone', 'Alpha-asarone', 'Essential oils', 'Sesquiterpenes']),
    benefits: JSON.stringify(['Mental clarity', 'Memory support', 'Phlegm transformation', 'Hearing improvement', 'Focus enhancement']),
    usage: 'Take 3-9g in decoction.',
    dosage: '3-9g dried rhizome in decoction',
    precautions: 'Contains asarone which may be hepatotoxic in high doses. Use moderate amounts.',
    scientificInfo: 'Research suggests cognitive-enhancing effects, though asarone safety concerns limit use.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Phytomedicine 2018']),
    relatedRemedies: JSON.stringify(['Polygala', 'Poria', 'Bamboo Shavings']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Dragon Bone (Long Gu)',
    description: 'A heavy, mineral-based substance that calms the spirit, anchors Yang, and astringes essence.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Fossilized bone (calcium carbite)', 'Calcium', 'Phosphorus', 'Trace minerals']),
    benefits: JSON.stringify(['Anxiety relief', 'Sleep improvement', 'Palpitation relief', 'Spirit calming', 'Sweating control']),
    usage: 'Take 15-30g in decoction (cook first for 20-30 minutes before adding other herbs).',
    dosage: '15-30g in decoction (pre-cook)',
    precautions: 'Heavy and astringent. Avoid with exterior conditions or constipation.',
    scientificInfo: 'Provides minerals and has traditional use for calming purposes.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2015', 'Chinese Medicine 2017']),
    relatedRemedies: JSON.stringify(['Oyster Shell', 'Sour Jujube Seed', 'Schisandra']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Oyster Shell (Mu Li)',
    description: 'A mineral that calms the spirit, anchors Yang, softens hardness, and astringes.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Ostrea shell (calcium carbonate)', 'Calcium', 'Magnesium', 'Trace minerals']),
    benefits: JSON.stringify(['Anxiety relief', 'Thyroid nodule support', 'Sweating control', 'Acid neutralization', 'Spirit anchoring']),
    usage: 'Take 15-30g in decoction (cook first). Calcined form (Duan Mu Li) for acid and astringency.',
    dosage: '15-30g in decoction (pre-cook)',
    precautions: 'Very cold and heavy. Avoid with cold conditions.',
    scientificInfo: 'Provides calcium and has traditional use for calming and softening masses.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2016', 'Chinese Medicine 2018']),
    relatedRemedies: JSON.stringify(['Dragon Bone', 'Scrophularia', 'Prunella']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Prunella (Xia Ku Cao)',
    description: 'A cooling herb that clears liver fire, dissipates nodules, and lowers blood pressure.',
    category: 'TCM Herb',
    ingredients: JSON.stringify(['Prunella vulgaris spike', 'Rosmarinic acid', 'Ursolic acid', 'Flavonoids', 'Triterpenes']),
    benefits: JSON.stringify(['Thyroid nodule support', 'Blood pressure reduction', 'Eye health', 'Heat clearing', 'Inflammation reduction']),
    usage: 'Take 9-15g in decoction or as tea.',
    dosage: '9-15g dried herb in decoction',
    precautions: 'Cold in nature. Avoid with Spleen and Stomach deficiency.',
    scientificInfo: 'Research shows antithyroid antibody-reducing and antihypertensive effects.',
    references: JSON.stringify(['Journal of Ethnopharmacology 2017', 'Phytomedicine 2019']),
    relatedRemedies: JSON.stringify(['Oyster Shell', 'Scrophularia', 'Chrysanthemum']),
    evidenceLevel: 'Moderate'
  }
]
