// Homeopathic and Bach Flower Remedies
export const homeopathicRemedies = [
  {
    name: 'Arnica Montana (Homeopathic)',
    description: 'Leading homeopathic remedy for trauma, bruising, and muscle soreness.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Arnica montana', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Bruise reduction', 'Trauma recovery', 'Muscle soreness', 'Post-surgical healing', 'Shock relief']),
    usage: 'Take 3-5 pellets under tongue as needed. Common potencies: 30C, 200C.',
    dosage: '3-5 pellets, 3-4x daily or as needed',
    precautions: 'Homeopathic doses are highly diluted. Do not use herbal arnica internally.',
    scientificInfo: 'Mixed research on homeopathic arnica; mechanism controversial.',
    references: JSON.stringify(['Cochrane Database 2019', 'Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Arnica Topical', 'Bromelain', 'Comfrey']),
    evidenceLevel: 'Limited'
  },
  {
    name: 'Nux Vomica',
    description: 'Homeopathic remedy for digestive upset, hangover, and overindulgence symptoms.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Strychnos nux-vomica', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Digestive relief', 'Nausea reduction', 'Hangover support', 'Irritability relief', 'Sleep improvement']),
    usage: 'Take 3-5 pellets under tongue. Common potencies: 30C, 200C.',
    dosage: '3-5 pellets as needed',
    precautions: 'Safe in homeopathic dilution. Crude form is toxic.',
    scientificInfo: 'Traditional homeopathic use; scientific evidence limited.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Ginger', 'Peppermint', 'Digestive Bitters']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Oscillococcinum',
    description: 'Popular homeopathic remedy for flu-like symptoms and immune support.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Anas barbariae', 'Highly diluted 200CK']),
    benefits: JSON.stringify(['Flu symptom reduction', 'Duration shortening', 'Immune support', 'Body ache relief']),
    usage: 'Take at first sign of flu symptoms. One tube under tongue.',
    dosage: 'One tube every 6 hours at onset of symptoms',
    precautions: 'Extremely diluted. Controversial efficacy.',
    scientificInfo: 'Cochrane review found weak evidence for modest reduction in illness duration.',
    references: JSON.stringify(['Cochrane Database 2015']),
    relatedRemedies: JSON.stringify(['Elderberry', 'Echinacea', 'Zinc']),
    evidenceLevel: 'Limited'
  },
  {
    name: 'Rhus Toxicodendron',
    description: 'Homeopathic remedy for joint stiffness, arthritis, and restlessness.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Poison ivy/oak', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Joint stiffness relief', 'Arthritis support', 'Restless leg relief', 'Skin conditions', 'Pain that improves with movement']),
    usage: 'Take 3-5 pellets under tongue. Best for stiffness worse on first movement.',
    dosage: '3-5 pellets, 3-4x daily',
    precautions: 'Safe in homeopathic dilution. Crude form causes contact dermatitis.',
    scientificInfo: 'Traditional homeopathic use; minimal scientific evidence.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Bryonia', 'Ruta', 'Turmeric']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bryonia Alba',
    description: 'Homeopathic remedy for pain worse with movement, dry cough, and headaches.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['White bryony', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Pain worse with movement', 'Dry cough relief', 'Headache relief', 'Joint pain', 'Constipation']),
    usage: 'Take 3-5 pellets. For pain that worsens with any movement.',
    dosage: '3-5 pellets, 3-4x daily',
    precautions: 'Safe in homeopathic dilution.',
    scientificInfo: 'Traditional homeopathic use; limited research.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Rhus Tox', 'Belladonna', 'Ginger']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Belladonna',
    description: 'Homeopathic remedy for sudden high fevers, throbbing headaches, and inflammation.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Atropa belladonna', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Sudden fever reduction', 'Throbbing headache relief', 'Inflammation', 'Sore throat', 'Ear infections']),
    usage: 'Take at onset of sudden, intense symptoms. Common potencies: 30C, 200C.',
    dosage: '3-5 pellets every 15-30 minutes initially, then less frequently',
    precautions: 'Safe in homeopathic dilution. Crude form is highly toxic.',
    scientificInfo: 'Traditional homeopathic use; limited scientific evidence.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Aconite', 'Ferrum Phos', 'Elderflower']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Ignatia Amara',
    description: 'Homeopathic remedy for grief, emotional shock, and mood swings.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['St. Ignatius bean', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Grief support', 'Emotional shock', 'Mood swings', 'Sighing and sobbing', 'Lump in throat sensation']),
    usage: 'Take for acute grief or emotional upset. Higher potencies for deeper issues.',
    dosage: '3-5 pellets as needed for emotional support',
    precautions: 'Safe in homeopathic dilution. Seek professional help for persistent emotional issues.',
    scientificInfo: 'Traditional homeopathic use for emotional conditions.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Bach Rescue Remedy', 'Natrum Mur', 'St. Johns Wort']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Chamomilla',
    description: 'Homeopathic remedy for teething, colic, and irritability in children.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['German chamomile', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Teething pain relief', 'Colic relief', 'Irritability in children', 'Earache', 'Restless sleep']),
    usage: 'Give to irritable, inconsolable children. Safe for infants.',
    dosage: '3 pellets dissolved in water for infants; 3-5 pellets for older children',
    precautions: 'Very safe. Popular pediatric remedy.',
    scientificInfo: 'Traditional homeopathic use; chamomile itself has research support.',
    references: JSON.stringify(['Complementary Therapies in Medicine 2018']),
    relatedRemedies: JSON.stringify(['Chamomile Tea', 'Pulsatilla', 'Calcarea Carb']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Pulsatilla',
    description: 'Homeopathic remedy for changeable symptoms, clingy children, and sinus issues.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Wind flower', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Changeable symptoms', 'Sinus congestion', 'Ear infections', 'Clingy children', 'Hormonal symptoms']),
    usage: 'Take for symptoms that change frequently and improve with open air.',
    dosage: '3-5 pellets, 3-4x daily',
    precautions: 'Very safe. Common pediatric and womens remedy.',
    scientificInfo: 'Traditional homeopathic use.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Chamomilla', 'Kali Bich', 'Sepia']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Apis Mellifica',
    description: 'Homeopathic remedy for bee stings, swelling, and burning/stinging pain.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Honeybee', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Bee sting relief', 'Swelling reduction', 'Burning pain', 'Allergic reactions', 'Urinary tract infections']),
    usage: 'Take immediately for stings and allergic swelling. Works on like-cures-like principle.',
    dosage: '3-5 pellets every 15 minutes initially for acute reactions',
    precautions: 'For minor reactions only. Seek emergency care for severe allergic reactions.',
    scientificInfo: 'Based on homeopathic like-cures-like principle.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Ledum', 'Urtica Urens', 'Benadryl']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Ledum Palustre',
    description: 'Homeopathic remedy for puncture wounds, insect bites, and bruising.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Marsh tea', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Puncture wound healing', 'Insect bite relief', 'Bruising', 'Tetanus prevention support', 'Joint pain']),
    usage: 'Take after puncture wounds, animal bites, or injections.',
    dosage: '3-5 pellets, 3-4x daily after injury',
    precautions: 'Does not replace tetanus vaccination or medical care for serious wounds.',
    scientificInfo: 'Traditional homeopathic use for puncture injuries.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Arnica', 'Apis', 'Hypericum']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Hypericum Perforatum (Homeopathic)',
    description: 'Homeopathic remedy for nerve injuries, crushing injuries, and nerve pain.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['St. Johns Wort', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Nerve injury healing', 'Crushing injury relief', 'Shooting nerve pain', 'Dental work recovery', 'Spine injuries']),
    usage: 'Take for injuries to nerve-rich areas (fingers, toes, spine, tailbone).',
    dosage: '3-5 pellets, 3-4x daily',
    precautions: 'Different from herbal St. Johns Wort. Does not interact with medications.',
    scientificInfo: 'Traditional homeopathic use for nerve-related injuries.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Arnica', 'Ledum', 'St. Johns Wort Herb']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach Rescue Remedy',
    description: 'Combination flower essence for stress, anxiety, and emotional emergencies.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Rock Rose', 'Impatiens', 'Clematis', 'Star of Bethlehem', 'Cherry Plum', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Acute stress relief', 'Panic calming', 'Emotional emergencies', 'Test anxiety', 'Travel nervousness']),
    usage: 'Take 4 drops under tongue or in water during stressful moments.',
    dosage: '4 drops as needed, up to 6x daily',
    precautions: 'Contains alcohol (brandy). Non-alcohol versions available.',
    scientificInfo: 'Limited research; mechanism attributed to vibrational energy of flowers.',
    references: JSON.stringify(['Complementary Therapies in Clinical Practice 2010']),
    relatedRemedies: JSON.stringify(['Ashwagandha', 'L-Theanine', 'Passionflower']),
    evidenceLevel: 'Limited'
  },
  {
    name: 'Bach Rock Rose',
    description: 'Flower essence for terror, panic, and extreme fear.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Helianthemum nummularium flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Panic relief', 'Terror calming', 'Nightmare recovery', 'Courage building', 'Emergency situations']),
    usage: 'Take 2 drops under tongue or in water as needed.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Contains trace alcohol. Part of Rescue Remedy formula.',
    scientificInfo: 'Bach flower remedy system; mechanism not scientifically established.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Rescue Remedy', 'Mimulus', 'Cherry Plum']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach Mimulus',
    description: 'Flower essence for known fears, shyness, and timidity.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Mimulus guttatus flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Known fear relief', 'Shyness support', 'Courage for specific situations', 'Phobia support', 'Timidity']),
    usage: 'Take 2 drops under tongue or in water for known, specific fears.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Contains trace alcohol. For known fears (vs. vague anxiety).',
    scientificInfo: 'Bach flower remedy system.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Rescue Remedy', 'Aspen', 'Rock Rose']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach Aspen',
    description: 'Flower essence for unknown fears, vague anxiety, and apprehension.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Populus tremula flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Vague anxiety relief', 'Unknown fear calming', 'Apprehension', 'Sense of dread', 'Night fears']),
    usage: 'Take 2 drops for vague, unexplained fears and anxiety.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Contains trace alcohol. For vague fears (vs. specific phobias).',
    scientificInfo: 'Bach flower remedy system.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Mimulus', 'Rock Rose', 'Cherry Plum']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach White Chestnut',
    description: 'Flower essence for racing thoughts, mental chatter, and insomnia from thinking.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Aesculus hippocastanum flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Racing thought calming', 'Mental chatter quieting', 'Sleep improvement', 'Mental peace', 'Worry cycle breaking']),
    usage: 'Take 2 drops for persistent, unwanted thoughts keeping you awake.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Contains trace alcohol.',
    scientificInfo: 'Bach flower remedy system.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Passionflower', 'Valerian', 'L-Theanine']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach Olive',
    description: 'Flower essence for exhaustion, mental and physical fatigue after long strain.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Olea europaea flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Exhaustion recovery', 'Energy restoration', 'Post-illness fatigue', 'Burnout recovery', 'Vitality renewal']),
    usage: 'Take 2 drops during or after periods of exhaustion.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Contains trace alcohol. Address underlying causes of exhaustion.',
    scientificInfo: 'Bach flower remedy system.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Ashwagandha', 'Rhodiola', 'B Vitamins']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach Walnut',
    description: 'Flower essence for life transitions, protection from change, and breaking old patterns.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Juglans regia flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Transition support', 'Change adaptation', 'Pattern breaking', 'Protection during change', 'Moving forward']),
    usage: 'Take 2 drops during major life changes or when breaking habits.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Contains trace alcohol.',
    scientificInfo: 'Bach flower remedy system.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Rescue Remedy', 'Star of Bethlehem', 'Honeysuckle']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Bach Star of Bethlehem',
    description: 'Flower essence for shock, trauma, and grief - past or present.',
    category: 'Flower Essence',
    ingredients: JSON.stringify(['Ornithogalum umbellatum flower essence', 'Brandy (preservative)']),
    benefits: JSON.stringify(['Trauma healing', 'Shock recovery', 'Grief support', 'Past trauma release', 'Comfort after loss']),
    usage: 'Take 2 drops after any shock or trauma, recent or from the past.',
    dosage: '2 drops, up to 4x daily',
    precautions: 'Part of Rescue Remedy. Seek professional help for severe trauma.',
    scientificInfo: 'Bach flower remedy system.',
    references: JSON.stringify(['Bach Centre Literature']),
    relatedRemedies: JSON.stringify(['Rescue Remedy', 'Ignatia', 'Walnut']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tissue Salt Mag Phos',
    description: 'Biochemic tissue salt for muscle cramps, nerve pain, and spasms.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['Magnesium phosphate 6X']),
    benefits: JSON.stringify(['Muscle cramp relief', 'Nerve pain', 'Menstrual cramps', 'Headaches', 'Restless legs']),
    usage: 'Dissolve 4 tablets under tongue. Can take in warm water for faster action.',
    dosage: '4 tablets, 3-4x daily',
    precautions: 'Low dose mineral supplement. Generally very safe.',
    scientificInfo: 'Biochemic medicine system by Dr. Schuessler; provides microdose magnesium.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['Magnesium', 'Cramp Bark', 'Calcium']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tissue Salt Calc Phos',
    description: 'Biochemic tissue salt for bone health, growth, and convalescence.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['Calcium phosphate 6X']),
    benefits: JSON.stringify(['Bone health', 'Teeth strength', 'Growth support', 'Recovery from illness', 'Anemia support']),
    usage: 'Dissolve 4 tablets under tongue.',
    dosage: '4 tablets, 3-4x daily',
    precautions: 'Low dose mineral supplement. Safe for children.',
    scientificInfo: 'Biochemic medicine; provides microdose calcium phosphate.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['Calcium', 'Vitamin D', 'Silica']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tissue Salt Ferrum Phos',
    description: 'Biochemic tissue salt for first stage of inflammation, fevers, and anemia.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['Iron phosphate 6X']),
    benefits: JSON.stringify(['Early stage inflammation', 'Mild fever', 'Anemia support', 'First aid remedy', 'Oxygenation support']),
    usage: 'Take at very first sign of cold/flu or inflammation.',
    dosage: '4 tablets every 15-30 minutes initially, then less frequently',
    precautions: 'Low dose iron. First-line tissue salt for acute conditions.',
    scientificInfo: 'Biochemic medicine; provides microdose iron for inflammation support.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['Iron', 'Aconite', 'Belladonna']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tissue Salt Kali Phos',
    description: 'Biochemic tissue salt for nervous exhaustion, stress, and mental fatigue.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['Potassium phosphate 6X']),
    benefits: JSON.stringify(['Nervous exhaustion', 'Mental fatigue', 'Stress support', 'Insomnia', 'Brain fog']),
    usage: 'Dissolve 4 tablets under tongue for mental and nervous fatigue.',
    dosage: '4 tablets, 3-4x daily',
    precautions: 'Low dose potassium. Safe nerve tonic.',
    scientificInfo: 'Biochemic medicine; the "nerve nutrient" tissue salt.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['B Vitamins', 'Magnesium', 'Ashwagandha']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tissue Salt Nat Mur',
    description: 'Biochemic tissue salt for fluid balance, grief, and cold sores.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['Sodium chloride 6X']),
    benefits: JSON.stringify(['Fluid balance', 'Cold sores', 'Grief support', 'Hay fever', 'Dry skin']),
    usage: 'Dissolve 4 tablets under tongue.',
    dosage: '4 tablets, 3-4x daily',
    precautions: 'Microdose sodium chloride. Generally safe.',
    scientificInfo: 'Biochemic medicine; supports water distribution in tissues.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['Electrolytes', 'Lysine', 'Ignatia']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Tissue Salt Silica',
    description: 'Biochemic tissue salt for skin, hair, nails, and pushing out splinters.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['Silicon dioxide 6X']),
    benefits: JSON.stringify(['Hair strength', 'Nail health', 'Skin clarity', 'Splinter expulsion', 'Scar reduction']),
    usage: 'Dissolve 4 tablets under tongue.',
    dosage: '4 tablets, 3-4x daily',
    precautions: 'Avoid with implants or foreign objects you dont want expelled.',
    scientificInfo: 'Biochemic medicine; supports connective tissue.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['Silica Supplement', 'Horsetail', 'Biotin']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Cell Salt Combination',
    description: 'All 12 Schuessler tissue salts combined for general mineral support.',
    category: 'Tissue Salt',
    ingredients: JSON.stringify(['All 12 tissue salts: Calc Fluor, Calc Phos, Calc Sulph, Ferrum Phos, Kali Mur, Kali Phos, Kali Sulph, Mag Phos, Nat Mur, Nat Phos, Nat Sulph, Silica']),
    benefits: JSON.stringify(['General mineral support', 'Overall vitality', 'Foundation nutrition', 'Cellular health', 'Tissue function']),
    usage: 'Take daily as general mineral support.',
    dosage: '4 tablets, 2-3x daily',
    precautions: 'Low dose minerals. Safe for daily use.',
    scientificInfo: 'Provides all 12 tissue salts for comprehensive cellular support.',
    references: JSON.stringify(['Schuessler Biochemic Tissue Salts']),
    relatedRemedies: JSON.stringify(['Trace Minerals', 'Multivitamin', 'Mineral Complex']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Calendula (Homeopathic)',
    description: 'Homeopathic remedy for wound healing, cuts, and surgical recovery.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Calendula officinalis', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Wound healing', 'Surgical recovery', 'Cut healing', 'Antiseptic effects', 'Scar prevention']),
    usage: 'Take internally and use topical preparations for wound healing.',
    dosage: 'Internal: 3-5 pellets 3x daily. Topical: as needed',
    precautions: 'Do not use on deep wounds that need to heal from inside.',
    scientificInfo: 'Herbal calendula has documented wound-healing properties.',
    references: JSON.stringify(['Journal of Clinical and Aesthetic Dermatology 2018']),
    relatedRemedies: JSON.stringify(['Calendula Herbal', 'Arnica', 'Hypericum']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Calcarea Carbonica',
    description: 'Constitutional homeopathic remedy for slow metabolism and developmental support.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Calcium carbonate from oyster shell', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Slow metabolism support', 'Developmental issues', 'Bone health', 'Cold intolerance', 'Anxiety with exhaustion']),
    usage: 'Constitutional remedy - best prescribed by homeopath.',
    dosage: 'As prescribed by practitioner',
    precautions: 'Constitutional remedy - individual assessment recommended.',
    scientificInfo: 'Major polycrest remedy in classical homeopathy.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Silica', 'Phosphorus', 'Sulphur']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Sulphur (Homeopathic)',
    description: 'Major constitutional remedy for skin conditions and detoxification.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Elemental sulphur', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Skin conditions', 'Detoxification', 'Digestive issues', 'Intellectual types', 'Warmth intolerance']),
    usage: 'Constitutional remedy - often used to start treatment or clear reactions.',
    dosage: 'As prescribed by practitioner',
    precautions: 'May cause temporary aggravation of symptoms (healing crisis).',
    scientificInfo: 'One of the major polycrest remedies in homeopathy.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Calcarea Carb', 'Lycopodium', 'Phosphorus']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Lycopodium',
    description: 'Constitutional homeopathic remedy for digestive issues and lack of confidence.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Club moss spores', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Digestive bloating', 'Liver support', 'Confidence issues', 'Right-sided symptoms', 'Anticipatory anxiety']),
    usage: 'Constitutional remedy - individual assessment recommended.',
    dosage: 'As prescribed by practitioner',
    precautions: 'Constitutional remedy - best used with professional guidance.',
    scientificInfo: 'Major polycrest remedy for digestive and emotional symptoms.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Sulphur', 'Phosphorus', 'Nux Vomica']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Sepia',
    description: 'Homeopathic remedy for hormonal imbalances and exhaustion in women.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Cuttlefish ink', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Hormonal balance', 'Menopause support', 'PMS relief', 'Exhaustion', 'Indifference to loved ones']),
    usage: 'Constitutional remedy - commonly used for female hormonal issues.',
    dosage: 'As prescribed by practitioner',
    precautions: 'Constitutional remedy - professional assessment recommended.',
    scientificInfo: 'Major remedy in classical homeopathy for hormonal conditions.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Pulsatilla', 'Natrum Mur', 'Lachesis']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Aconitum Napellus',
    description: 'Homeopathic remedy for sudden onset symptoms, panic, and shock.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Monkshood', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Sudden symptom onset', 'Panic attacks', 'Shock', 'Fear of death', 'Beginning of colds']),
    usage: 'Take at very first onset of symptoms or during acute panic.',
    dosage: '3-5 pellets every 15 minutes initially for acute conditions',
    precautions: 'Safe in homeopathic dilution. Crude form is highly toxic.',
    scientificInfo: 'First-line remedy for sudden, intense onset of any condition.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Belladonna', 'Ferrum Phos', 'Rescue Remedy']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Gelsemium',
    description: 'Homeopathic remedy for flu with weakness, anticipatory anxiety, and stage fright.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Yellow jasmine', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Flu with weakness', 'Anticipatory anxiety', 'Stage fright', 'Drowsy flu', 'Trembling']),
    usage: 'Take for flu with great weakness or for anticipatory anxiety.',
    dosage: '3-5 pellets, 3-4x daily',
    precautions: 'Safe in homeopathic dilution. Crude form is toxic.',
    scientificInfo: 'Major flu remedy in homeopathy; also used for performance anxiety.',
    references: JSON.stringify(['Homeopathy 2017']),
    relatedRemedies: JSON.stringify(['Oscillococcinum', 'Bryonia', 'Argentum Nitricum']),
    evidenceLevel: 'Traditional'
  },
  {
    name: 'Argentum Nitricum',
    description: 'Homeopathic remedy for anticipatory anxiety, digestive nervousness, and sugar cravings.',
    category: 'Homeopathic',
    ingredients: JSON.stringify(['Silver nitrate', 'Highly diluted per homeopathic preparation']),
    benefits: JSON.stringify(['Anticipatory anxiety', 'Exam nerves', 'Digestive nervousness', 'Diarrhea from anxiety', 'Phobias']),
    usage: 'Take before anxiety-provoking events or for chronic anticipatory anxiety.',
    dosage: '3-5 pellets before stressful events or 3x daily',
    precautions: 'Safe in homeopathic dilution.',
    scientificInfo: 'Major remedy for performance anxiety and nervous digestive symptoms.',
    references: JSON.stringify(['Homeopathy 2018']),
    relatedRemedies: JSON.stringify(['Gelsemium', 'Lycopodium', 'Rescue Remedy']),
    evidenceLevel: 'Traditional'
  }
]
