name: org-osv

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run OSV scan
        uses: google/osv-scanner-action/osv-scanner-action@a30b4c310bacb7c0635e316e0720e23f0b791cf8
        with:
          scan-args: |-
            --output=results.json
            --format=json
            --recursive
            ./
        continue-on-error: true

      - name: Report OSV results
        uses: google/osv-scanner-action/osv-reporter-action@a30b4c310bacb7c0635e316e0720e23f0b791cf8
        with:
          scan-args: |-
            --output=results.sarif
            --new=results.json
            --gh-annotations=false
            --fail-on-vuln=false
